sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js: "8"
install:
  - npm install
after_success:
  - npm run cover
  - npm run report
branches:
  only: master
