sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
    - ~/.cache
notifications:
  email: false
node_js: "8"
install:
  - npm install
script:
  - npm run check-cover
  - npm run build
  - npm run gh-page
after_success:
  - npm run report
branches:
  only: master
